apiVersion: v1
kind: Service
metadata:
  name: devops-diplom-app-service
  namespace: custom
spec:
  selector:
    app: devops-diplom-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
