env:
  IMAGE_NAME: wilderwein123/devops-diplom-app
  KUBE_NAMESPACE: custom
  KUBE_DEPLOYMENT: k8s/deployment.yaml
  KUBE_SERVICE: k8s/service.yaml
  
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: debug
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/devops-diplom-app:latest
            ${{ secrets.DOCKER_USERNAME }}/devops-diplom-app:${{ github.ref_name }}

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube/

      - name: install yc
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Authenticate to Kubernetes cluster
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > ${HOME}/.kube/config
          kubectl config view
          kubectl get nodes
          
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=kubeconfig
          kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml -n custom
          kubectl --kubeconfig=kubeconfig apply -f k8s/service.yaml -n custom
          kubectl --kubeconfig=kubeconfig rollout status deployment/devops-diplom-app -n custom
