env:
  IMAGE_NAME: tud777777/devops_diplom
  KUBE_NAMESPACE: netology
  KUBE_DEPLOYMENT: nginx-test-app-deployment.yaml
  KUBE_SERVICE: nginx-test-app-service.yaml
  
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nginx-test-app:latest
            ${{ secrets.DOCKER_USERNAME }}/nginx-test-app:${{ github.ref_name }}

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes Context
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=kubeconfig
          kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml -n netology
          kubectl --kubeconfig=kubeconfig apply -f k8s/service.yaml -n netology
          kubectl --kubeconfig=kubeconfig rollout status deployment/nginx-test-app -n netology
